site_name: PROJECT_NAME Documentation
pages:
  - Home: index.md
  - Administrator Docs:
    - Overview: admin/index.md
  - Development Docs:
    - Overview: dev/index.md
  - User Docs:
    - Overview: user/index.md
theme: united
extra_css:
  - css/extra.css
site_dir: docsite